name: Build
on: [push, pull_request]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: bring 
        uses: dante-ev/latex-action@latest
        with:
          root_file: bring.tex
          compiler: pdflatex
          args: -interaction=nonstopmode
      - name: program-fees
        uses: dante-ev/latex-action@latest
        with:
          root_file: program-fees.tex
          compiler: pdflatex
          args: -interaction=nonstopmode
      - name: create build directory 
        run: mkdir build
      - name: move built assets 
        run: mv *.pdf build
      - name: Publish to GitHub pages
        if: success() 
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
